export const career = {
  summary:
    "Fifteen years in IT — most of it spent inside the engine room of Guidewire, the platform that runs much of the world's property & casualty insurance. Started as a fresher writing Java for Pfizer's drug-discovery pipeline, ended up leading conversions of nine million claims for a Canadian public-sector insurer. Built accelerators, mentored teams, flew onsite, shipped to production. Then walked away — twice — because the most valuable system I was ever going to build was my own life.",
  experiences: [
    {
      company: "Stratus Technologies",
      role: "Guidewire Senior Tech Lead",
      years: "2022–2024",
      location: "Remote",
      highlights: [
        "Two-year run as Senior Tech Lead — the last corporate chapter.",
        "Walked out for good in September 2024 to build life on my own terms.",
      ],
      logo: "",
    },
    {
      company: "HCL Technologies",
      role: "Guidewire Senior Tech Lead",
      years: "2020–2022",
      location: "Chennai",
      highlights: [
        "Returned to HCL — the place where the engineering instinct first sharpened.",
        "Stepped away in 2022; took a six-month sabbatical before the Stratus chapter.",
      ],
      logo: "",
    },
    {
      company: "Ernst & Young (EY GDS)",
      role: "Guidewire Configuration, Integration & Data Conversion Lead",
      years: "2017–2020",
      location: "Chennai",
      highlights: [
        "Big4 consulting on full-suite Guidewire implementations — Auto, Property, Workers Compensation.",
        "Led data conversion streams: legacy mainframe → Guidewire across millions of policies and claims.",
        "Built the case for personal freedom one corporate deadline at a time.",
      ],
      logo: "",
    },
    {
      company: "HCL Technologies",
      role: "Software Engineer → Senior Developer → Technical Lead",
      years: "2010–2017",
      location: "Chennai · Canada (L1, 2015–2017)",
      highlights: [
        "Joined as a fresher in 2010 — Oracle training, then Pfizer's drug-discovery support on Java.",
        "Pivoted into Guidewire in 2012; certified on ClaimCenter 7.x (technical + functional).",
        "Flew to Canada on L1 in 2015 as Senior Tech Lead — direct client rapport, onsite team of 10.",
        "~10 projects across Europe and Asia-Pacific clients before the second exit.",
      ],
      logo: "",
    },
  ],
  projects: [
    {
      title: "9 Million Claims — Legacy to Guidewire",
      client: "Public Sector Insurer",
      domain: "Workers Comp · Canada",
      role: "Data Conversion Lead · Onsite Coordinator · SME (GWCM, GWCC, Integrations)",
      impact:
        "Migrated ~9M claims from a mainframe legacy system into Guidewire — the kind of migration that rewrites how an entire public-sector insurer runs.",
      tech: ["Guidewire Suite 7.x", "Gosu", "Core Java", "Custom Plugins", "Batch Process"],
      year: 2015,
    },
    {
      title: "Migrate to Archive — 6.4M Claims",
      client: "US P&C Insurer",
      domain: "Claims Archival",
      role: "Senior Developer · Performance & Concurrency Owner",
      impact:
        "Archived 6.4 million claims from a Guidewire Data Migration instance into the Production archive store. Resolved deadlocks on multi-threaded archive batches and entity duplication issues that surfaced only in prod.",
      tech: ["Guidewire ClaimCenter", "Linux", "Online Batch", "BCP"],
      year: 2018,
    },
    {
      title: "Commercial Property LOB — Auto & Property",
      client: "US P&C Insurer",
      domain: "ClaimCenter Implementation",
      role: "Senior Developer · Offshore Coordinator · Code Reviewer",
      impact:
        "Led a 10-member team running production support and enhancements on ClaimCenter 8.x. Implemented Commercial Property LOB, Lexis Nexis Police Reporting and Vehicle Prefill, financials and payment reconciliations.",
      tech: ["Guidewire Suite 8.x", "Gosu", "Lexis Nexis APIs", "PCF"],
      year: 2014,
    },
    {
      title: "Claims Archival — Live-File Retrieval",
      client: "US P&C Insurer",
      domain: "Claims Archival",
      role: "Designer · Developer",
      impact:
        "Built an archival pipeline so that archived claims could still be viewed and retrieved as if they were live — cut network usage through data compression.",
      tech: ["Guidewire ClaimCenter", "Gosu", "Batch", "Data Model"],
      year: 2016,
    },
    {
      title: "Guidewire Accelerators — Claim Cloner · Admin Data Loader · Data Subset Tool",
      client: "Reusable across Guidewire engagements",
      domain: "Internal Tooling",
      role: "Designer · Developer",
      impact:
        "Built three Java-based accelerators that became reusable across every Guidewire product the firm touched.",
      tech: ["Core Java", "Guidewire APIs"],
      year: 2017,
    },
    {
      title: "Claims Transformation & L3 Support",
      client: "Public Sector Insurer",
      domain: "Personal Insurance (Auto, Home, BOP, Worker Comp) · Finland",
      role: "L3 Support Analyst · Developer",
      impact:
        "Integration points to external systems for incoming/outgoing money (BillingCenter) and cheque printing. Root-cause-analysis, major-incident management, and zero-downtime patch deployments for a national insurer.",
      tech: ["Guidewire ClaimCenter 5.x", "Integrations", "BillingCenter"],
      year: 2013,
    },
    {
      title: "Pfizer — Drug Discovery Application Support",
      client: "Pfizer",
      domain: "Healthcare · Pharma",
      role: "Software Engineer (Java)",
      impact:
        "First professional gig out of college — Java support and development for Pfizer's drug-discovery phase application. Where the discipline started.",
      tech: ["Core Java", "Oracle"],
      year: 2010,
    },
  ],
  skills: [
    { name: "Core Java", category: "language" },
    { name: "Gosu", category: "language" },
    { name: "SQL & PL/SQL", category: "language" },
    { name: "Guidewire ClaimCenter", category: "tool" },
    { name: "Guidewire PolicyCenter", category: "tool" },
    { name: "Guidewire ContactManager", category: "tool" },
    { name: "GW Studio", category: "tool" },
    { name: "Eclipse", category: "tool" },
    { name: "Toad", category: "tool" },
    { name: "Oracle DB", category: "tool" },
    { name: "MS SQL Server", category: "tool" },
    { name: "Jetty / JBoss / Tomcat / Weblogic", category: "tool" },
    { name: "SVN · Perforce · Git", category: "tool" },
    { name: "P&C Insurance", category: "domain" },
    { name: "Workers Compensation", category: "domain" },
    { name: "Claims Archival & Data Conversion", category: "domain" },
    { name: "ClaimCenter v8 → v10 Upgrades", category: "domain" },
    { name: "Agile · SDLC", category: "domain" },
  ],
};
