export const farm = {
  name: "Nandhavanam Farm",
  story:
    "In 2019 I bought a piece of land at the foothills of Kodaikanal — the very beginning of the Western Ghats — and called it Nandhavanam, the garden. I was still in IT then, still flying onsite. The land was an answer to a question I hadn't yet learned how to ask. By the time I left the corporate world for good in 2024, Nandhavanam had quietly become home. We moved out of the city, built our house mid-woods, and started learning natural farming the slow way — the only way it teaches. Today the farm is the centre of gravity for everything else: family, food, work, silence. It is also a brand, a school, and a promise — to the next generation, and to the soil.",
  philosophy: [
    "Live close to nature. The nervous system was never designed for the city.",
    "Grow your own food. The most radical act left in this century.",
    "Self-sustainable, healthy living — not as an aesthetic, as a daily practice.",
    "Leave the next generation a hopeful inheritance: real food, real soil, real silence — no chemicals, no pesticides.",
    "Marry old practices with new tools. Natural farming + technology + modern training — the farm of the future is ancient and connected.",
  ],
  whatWeGrow: [
    "Coconuts (and value-added coconut products)",
    "Bananas",
    "Native-breed cows and bulls",
    "Poultry",
  ],
  gallery: [
    "/images/farm/IMG_3862.JPG",
    "/images/farm/IMG_4183.JPG",
    "/images/farm/IMG_4189.JPG",
    "/images/farm/IMG_4190.JPG",
    "/images/farm/IMG_5327.JPG",
    "/images/farm/IMG_5331.JPG",
    "/images/farm/IMG_6178.JPG",
    "/images/farm/IMG_6198.JPG",
    "/images/farm/IMG_6651.JPG",
    "/images/farm/IMG_6671.JPG",
    "/images/farm/IMG_6716.JPG",
    "/images/farm/IMG_6717.JPG",
    "/images/farm/IMG_7352.JPG",
    "/images/farm/IMG_7904.JPG",
    "/images/farm/IMG_7911.JPG",
    "/images/farm/IMG_9335.JPG",
    "/images/farm/IMG_9338.JPG",
    "/images/farm/IMG_9345.JPG",
    "/images/farm/IMG_9929.JPG",
    "/images/farm/IMG_9930.JPG",
    "/images/farm/IMG_E9547.JPG",
    "/images/farm/IMG_E9548.JPG",
    "/images/farm/IMG_E9549.JPG",
  ],
  location:
    "Batlagundu, on the border of Theni and Dindigul districts — foothills of Kodaikanal, the start of the Western Ghats. Tamil Nadu, India.",
  link: "https://www.nandhavanamfarm.com",
  social: {
    facebook: "https://www.facebook.com/nandhavanamnaturalfarms/",
    googleBusiness: "https://share.google/Qdg0U5TqBYzZRrux2",
  },
};
